### PR TITLE
Create decentralized-identifiers.md

### PR DESCRIPTION
**Pull request by OR13**
- [live](https://mermaid.live/edit#pako:eNqlVMtqwzAQ_BWhU9uEQK8mBALuIX1AwbQnXRRp44jIklnJLiYk3175RZImxS61Maxmx6thdqU9FVYCjajQ3LlY8RR5xkz9NgiJVzHZM0PCM58v184jF36xaJFJk1ayXSE4q0u4u2fmcFHgA_VAjZrRl5GAsAmfETdKxVYUGRg_VtOEvCrnj5-AaqME98qaN_BbK4-EF34bKnXoMN05wBMwyBc852ulla9WprQjNzn9FIOGdNxPO6iWKQLUvlyQE8BSCTgS1wZ9UiBw35jbrs8a1wJFLi8IEoLBquyws45cy_lDoyck8ahMSnyVw3nzhDUerdaAPfperLUSL1CRvI-ev3Z9tqxVVCe5YXSwyv0PrZ0b_xXYQZ2lT0bmVtW-h53O55PRR0bJbNYFIXUr_9AQMm6qsLg2k5kbBl9XDppHMgc1JP2k9G79shuhU5oBZlzJcHk0ljIazlMGjEYhlBx3jAZXAi8cNJtURtDIYwFT2k5Xd9fQaMO1g8M3EaJ9pw)
 
 
Screen Shot 2022-10-14 at 3 22 12 PM

### CODE REVIEW

**Comment by thomas-tran** [comment]
In my opinion, the identifier component should be like this

[](https://mermaid.live/edit#pako:eNqtVUFuwjAQ_ErkE21TpF5RBRcuqEWqxNWXrb2kVhMb2Q5SVJW3dyEOcUJIhdociO3szI7Hk_DFhJHIZkzk4NxSQWah4Jrr0zxZrSRqr3yVfHGd0PX8rLRHuwWB83m9tPFW6SyRStbz5Wq5NKIsCJhII7j-jvgC3Zs1eyXRtrTw7rwF4RvWB2ERPE5esFqDhgyPfBu0eyUw-SzcXastAMqdvA1g0Zl8P4Z4NyYPxRJJnNqPd4jqLWbKkVOT1kIVBmljWV1jq0WDHHBq443FEZtUsTPWR13AZl0lGfpJe0aXNkjMkXYVl0TonBQ2z3bh1EjvKy0fzkyHQemXJoVtPNboXhYOZ34XyroeuONveHLtCDrZaeCNfMgVuMXZfQ9ZO4m21vendvhMNnKeAw2uxbSvjWxP-29O-jfddO6DXf6LVaG70dmL0ET5G5MaUXRz3Y-Qu5rUftZCYK9HlbMnzpLpNAw6UbwBNxTU3-H3J3wBuopaN9pZygq0BShJn-3TG8WZ_yAWzmY0lLiFMvec0RapFEpvNpUWbOZtiSmr4xc-9Gy2hdzRKkpFG1uHv4Lj7fsHUkknDg)

**Comment by OR13** [comment]
@thomas-tran I like your additions, I how should we merge these?

If you suggest them as changes, I am happy to accept.

**Comment by thomas-tran** [comment]
@OR13 Here is the [live](https://mermaid.live/edit#pako:eNqtVcFu4jAQ_ZXIJ7qbVuoVVe2FC9pWqsTVl6k9zVpNbDQ2SBGCb-9AHOKEkBXq5kBsZ96b5-eXsBPKaRRzoUrwfmGgIKiklfY0z5ZLjTaYUGc7aTO-np6MDUifoPD5uVlaBTK2yLTRzXyxXCyc2lQMzLRT0u4Tvkj3Tm5rNFJHCx8-EKjQsv5WhBBw9gfrN7BQ4JFvhbQ1CrOvyt912iJgs9a3AQi9K7dTiA_nyliskcWZ7XSHpJ6wMJ6dmnUWmjjIW8uaGqpfWuSIU6vgCCdsMtXaUUi6ABV9JQWGWXdGlzZoLJF3lZYk6JIVts_W8dRY7ysvH85Mh1HplybFbdw36EEWDmd-H8v6Hvjjb3xy7Qh62WnhrXwoDfiXs_sBim6SbG3oT-PwmWziPEcaXIvpUBvbng_fnPxnuvncR7v8L1aD_kZnL0KT5G9KakLRz_UwQv5qUodZi4G9HlUpHqXIHh7ioBfFG3BjQf03_NcJX4Gtk9atdpGLCqkCo_mzfXqjpAh_mUWKOQ810JcUvD-ug01wq9oqMQ-0wVw02YtfeTH_hNLzKmrDu3qL_wPH2_4b0Gklyw) url , please help to merge into your diagram.

**Comment by OR13** [comment]
Screen Shot 2022-10-19 at 2 09 49 PM

[updated live](https://mermaid.live/edit#pako:eNqtVl1v2jAU_SuRn9rBKu0VVa0qsQe2IVVC21NejH1JLRI7ujZMUVV--24SmzghFKoOBDjX9-P43GPsVyaMBDZjIufWzhXPkBeprt-NJZkv5slrqhN63d8_ra1DLtzDQ2uZNNNKtk8I1uR7uLlN9VsvwW_ML-SoPUIaCQgb-mgxkmpuxK4A7a7FNEl-KesOfwDVRgnulNFLcC9GHhK-cy-UyVsvu1sL2Bku-gte8rXKlasWem-uLNIFzSGH7LqgLVRPGQLUvPScV4B7JeCQ2HYQJgUCdw257XPUuNawK2XPQQIRrPbeFnXkFM4HGj1JVg6VzhJXlRA3Txjt0OQ5YLA-79a5Ej-hSsow-vF3G2b3NYqqg0vSwap0A6yejc8C9CZP6XctS6Nq3qNKi4WsheWqrha5AG64gFDMp5GhVqxtaUQ_n0_3jGavaHt0aflwCb61xM-Sa541mggL3xb2tsPmA3yrrw8IYjkfsTYm986RcK7yR8hIuIA3HYXKD6aBstYHq8cQOcLUyhmEd2hSRWnQRVU4Zn0kGbibrkenNEjan7Sq2CWKzglhmCt91whvsyuPmQ6j0E9J8sv42kYPtHA45rferc-Brb_9zLkW9LQTwgN8nituH4_sO551D9HShvy0DB-TvdPPkQLnZDrERrRPhztn-jnc1PfRKv8rqwL7QWZPRBPp7z2oUYq-rocSsmeVOtSaF-x5qabsW8qSuzs_6EnxA3FjQr0c_qWJL7iuotIBe4y73RlRTR8Tt60T7ABbrLc6aSy_gStNjc33cJ6eoKkeOVVPM9NBdaXnRQxHhs-0I1RL2JQVgAVXkm6Mzd9SyugSVUDKZjSUHLcpI5GQH92uzKrSgs0c7mDK2g3sL5hstuG5JStIRb1Y-ito_fP2D8-hnOk)

**Comment by dhh1128** [comment]
I don't think we should confuse "identity" and "identifier." The methods on an identity service are creating identifiers, not identities, right?

**Comment by thomas-tran** [comment]
@dhh1128 In my perspective , the identity management service is used to create an identity or the identity card that contains properties such as a unique decentralized identifier (did) , the metadata (did doc) associate with it and optional other information.
An identity can be an organizational identity, a person, a group or a thing identity. For example, an organizational identity contains name, alias, type(tag), domain_url, business_address, did and did_doc.
```
interface IOrganization extends IIdentity
```
You can register the decentralized identifier (did) in the blockchain similar to the domain name in the domain registry. The identity itself can be stored off chain in the local database & secured cloud storage.

**Comment by dhh1128** [comment]
Is there a 1:1 relationship between "identity" and "identifier" in this design?

How would I model a situation where I rotate my identifier? Have I rotated my identity, or just changed the way I index into it? Can one identity have more than one identifier at the same time?

**Comment by thomas-tran** [comment]
In the real world, the physical wallet holds multiple identity cards such as a driver's license, employee id card, and medicare card. 

The digital wallet is similar to the physical wallet which can hold one or more identities depending on the different types of the wallet. For instance, the user's digital wallet has up to 10 identities, the cloud wallet has unlimited identities and an IoT device wallet has only one identity. 

Each identity has a unique identifier so the relationship between the identity and identifier is 1 to 1.

If your identity is compromised, to be specific, the private key that is used to authenticate to some services or websites is compromised. You will not rotate your identity or your identifier (did:elem:Zsxxxx), instead, you will rotate the key for authentication or assertion ( issue to a credential) in the identity metadata or identity document (did doc).

You may need to have different keys during the identity creation. 
For example 
Authentication: Secp256k1 allow access to website or services
Assertion: Ed25519 to issue credentials
Key Agreement: X25519 to create a secure communication channel between parties (DIDComm protocol)
Capability Invocation: Ed25519 to update the identity document (did doc) either to replace the authentication or assertion key
Capability Delegation: Ed22519 to delegate the capability to the other party to act on behalf.

The method update() in the identity provider will handle the key rotation using the capability invocation key. You must keep the Capability Invocation private key safely as it is the only way to rotate your key or to update the identity document in the registry (blockchain).

**Comment by dhh1128** [comment]
>In the real world, the physical wallet holds multiple identity cards such as a driver's license, employee id card, and medicare card. The digital wallet is similar to the physical wallet which can hold one or more identities depending on the different types of the wallet. For instance, the user's digital wallet has up to 10 identities, the cloud wallet has unlimited identities and an IoT device wallet has only one identity... Each identity has a unique identifier so the relationship between the identity and identifier is 1 to 1.

I don't think we are defining "identity" the same way.

When I became involved in the DID spec 6 years ago, one of the first lectures I got from the W3C CCG community was on the distinction between "identity" and "identifier." I don't remember who delivered the lecture, but whoever they were, they were right. I suggest that we stipulate that: A credential is not an identity (your driver's license and your passport both describe or attach to the same identity, which has a legal meaning quite different from the credential that proves it). An identifier is not an identity (my family calls me "Dan" in most cases, but "Daniel" if they're being formal; you may have a passport number and a driver's license and one or more DIDs that all point to the same identity). A profile is not an identity (it is rather a view or projection of an identity in a context). A pair of crypto keys is not identity (it is rather a way of proving or exercising identity).

This is not just a philosophical argument. As I write this, I have an email sitting in my inbox from YouTube, announcing that after many years and much effort, they've created the ability for users to choose and change their handles (identifiers). When I change handles (identifiers), I have clearly not changed my identity, since YouTube doesn't ask me to change my password and doesn't reset my history or library. There is a sameness (identity) that remains stable across the identifier change. It's taken YouTube over a decade to conclude that they shouldn't equate identity and identifiers; let's learn from their many-millions-of-dollars/euros/yen mistake. (BTW, numerous other services make this same mistake. But there are important examples of the other [correct] model. You can change your Twitter handle or your github handle without resetting your identity.)

I suggest that the interface in @OR13 's beautiful picture should have methods that are about creating and updating *identifiers* and their associated metadata (e.g., DID documents), but should not have methods that are about creating and updating identities. This doesn't really change the function signatures; it just changes the names to accurately reflect what's really going on -- because wallets don't actually create identities; they help you manage the artifacts associated with an identity that already exists. The (normal) scope of concern for one identity manager instance = 1 (pre-existing) identity. It is this identity that is associated with biometrics and similar things that unlock the wallet, and it is this entity that projects itself in various contexts using one identifier or another. It is this entity that gives the wallet its configuration and policy choices, and it is to this entity that the wallet owes allegiance. Its security model should be geared to protecting this identity, which has a broader meaning than just protecting one identifier worth of stuff; it must take into consideration how all the identifiers are or are not correlated, in order to do its protection and management job correctly. 

The normal work that's done to manage that identity is at the identifier level, which is more granular than a full identity. Providing that granularity -- and allowing it to exist comfortably without bogging the identity controller down with the underlying details -- is one of the value propositions of a digital wallet.

**Comment by thomas-tran** [comment]
@dhh1128  I think you are right 
@OR13 I've changed the name in the [live ](https://mermaid.live/edit#pako:eNqtVUFuwjAQ_ErkE21TpF4RggsX1CJV4urLYi-p1cRGtoMUIXh7F-KAAwkVajlA7Hhmd2YnZMeEkchGTOTg3ExBZqHgmuvTOpnPJWqv1gptsuM6oc94rLRHuwaBk0m9tfRW6SyRStbr2Xw2M6IsCJpII7jeR4wnQl99WrNVMqaFlfMWhG9YX4RF8Dh4x2oBGjI88i3RbpXA5LtwT3F3AVJu5KMQi87k28cwEqlPtb1famVMfq6RKUemDWI_VXAibfyrT9lq2mA7bFt6Y_GOZ6rYGOtbdcBm7W4y9IPLyLr15Uja4kMRPqcum3ubMEbq-YO2DxHXoVPArVlBzGuNv4rH4VzBhWNtJ9zxO9zpG0UrTpf-GgmQK3DT8xQ8ZJdFJO_WpdrriPDudDvK9Cf4tksaQnr9YKV_VUBJ6Kn0r8zuQas7khTF8n7HEU078tfJcr0Rvo5gyHF_gjl74ywZDsNFK6EP4Lry-zv8-YQvQFdR6aZ3lrICbQFK0l_86UHjzH8RC2cjupS4hjL3nJFEOgqlN8tKCzbytsSU1VkMLwU2WkPuaBelImGL8No4_ux_AERVNxQ) URL, please help to update the diagram

**Comment by OR13** [comment]
@thomas-tran I think the link you shared is stale... it does not have changes.

I think it's ok to do a find replace on "identity" to "identifier" and take the changes as WIP.

lets keep PR feedback focused on specific change requests and move discussion to discord or issues.

**Comment by Parsifal-M** [comment]
> > In the real world, the physical wallet holds multiple identity cards such as a driver's license, employee id card, and medicare card. The digital wallet is similar to the physical wallet which can hold one or more identities depending on the different types of the wallet. For instance, the user's digital wallet has up to 10 identities, the cloud wallet has unlimited identities and an IoT device wallet has only one identity... Each identity has a unique identifier so the relationship between the identity and identifier is 1 to 1.
> 
> I don't think we are defining "identity" the same way.
> 
> When I became involved in the DID spec 6 years ago, one of the first lectures I got from the W3C CCG community was on the distinction between "identity" and "identifier." I don't remember who delivered the lecture, but whoever they were, they were right. I suggest that we stipulate that: A credential is not an identity (your driver's license and your passport both describe or attach to the same identity, which has a legal meaning quite different from the credential that proves it). An identifier is not an identity (my family calls me "Dan" in most cases, but "Daniel" if they're being formal; you may have a passport number and a driver's license and one or more DIDs that all point to the same identity). A profile is not an identity (it is rather a view or projection of an identity in a context). A pair of crypto keys is not identity (it is rather a way of proving or exercising identity).
> 
> This is not just a philosophical argument. As I write this, I have an email sitting in my inbox from YouTube, announcing that after many years and much effort, they've created the ability for users to choose and change their handles (identifiers). When I change handles (identifiers), I have clearly not changed my identity, since YouTube doesn't ask me to change my password and doesn't reset my history or library. There is a sameness (identity) that remains stable across the identifier change. It's taken YouTube over a decade to conclude that they shouldn't equate identity and identifiers; let's learn from their many-millions-of-dollars/euros/yen mistake. (BTW, numerous other services make this same mistake. But there are important examples of the other [correct] model. You can change your Twitter handle or your github handle without resetting your identity.)
> 
> I suggest that the interface in @OR13 's beautiful picture should have methods that are about creating and updating _identifiers_ and their associated metadata (e.g., DID documents), but should not have methods that are about creating and updating identities. This doesn't really change the function signatures; it just changes the names to accurately reflect what's really going on -- because wallets don't actually create identities; they help you manage the artifacts associated with an identity that already exists. The (normal) scope of concern for one identity manager instance = 1 (pre-existing) identity. It is this identity that is associated with biometrics and similar things that unlock the wallet, and it is this entity that projects itself in various contexts using one identifier or another. It is this entity that gives the wallet its configuration and policy choices, and it is to this entity that the wallet owes allegiance. Its security model should be geared to protecting this identity, which has a broader meaning than just protecting one identifier worth of stuff; it must take into consideration how all the identifiers are or are not correlated, in order to do its protection and management job correctly.
> 
> The normal work that's done to manage that identity is at the identifier level, which is more granular than a full identity. Providing that granularity -- and allowing it to exist comfortably without bogging the identity controller down with the underlying details -- is one of the value propositions of a digital wallet.

Really good write-up on this :+1: I also agree.

**Pull request merged**
